import {chromium,webkit} from '@playwright/test';import {spawn} from 'node:child_process';import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=spawn(process.execPath,['tests/ui-server.mjs'],{stdio:'inherit'});await mkdir('outputs',{recursive:true});
for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:4399/');break}catch{await new Promise(r=>setTimeout(r,100))}}
try{for(const [engine,type] of [['chromium',chromium],['webkit',webkit]]){
const browser=await type.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4399/');await page.getByRole('heading',{name:'记录',exact:true}).waitFor();
await page.getByLabel('随手记录',{exact:true}).fill('为什么模型能学习 '+engine);await page.getByRole('button',{name:'保存记录',exact:true}).click();await page.locator('.card-title').filter({hasText:engine}).waitFor();
await page.getByLabel('随手记录',{exact:true}).fill('未提交草稿 '+engine);await page.reload();await page.getByLabel('随手记录',{exact:true}).waitFor();assert.equal(await page.getByLabel('随手记录',{exact:true}).inputValue(),'未提交草稿 '+engine);
await page.getByLabel('随手记录',{exact:true}).fill('');await page.getByRole('button',{name:'收起输入框'}).click();
await page.locator('.card').filter({hasText:engine}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('编辑记录',{exact:true}).fill('编辑草稿 '+engine);await page.getByRole('button',{name:'关闭编辑'}).click();await page.locator('.card').filter({hasText:engine}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();assert.equal(await page.getByLabel('编辑记录',{exact:true}).inputValue(),'编辑草稿 '+engine);await page.getByRole('button',{name:'放弃修改，恢复原文'}).click();await page.getByRole('button',{name:'关闭编辑'}).click();
await page.locator('nav [data-tab=settings]').click();await page.locator('summary').filter({hasText:'模型服务'}).click();await page.locator('input[name=baseUrl]').fill('https://models.example.com/v1');await page.locator('input[name=model]').fill('fixture');await page.locator('input[name=apiKey]').fill('fixture-key');await page.getByRole('button',{name:'保存并测试连接'}).click();await page.getByText('AI 已连接',{exact:true}).waitFor();
await page.screenshot({path:`outputs/${engine}-settings.png`,fullPage:true});
await page.locator('nav [data-tab=inbox]').click();await page.locator('.card').filter({hasText:engine}).click();await page.getByRole('button',{name:'现在推进',exact:true}).click();await page.getByText('先区分训练与推理',{exact:true}).waitFor();await page.screenshot({path:`outputs/${engine}-detail.png`});
await page.getByLabel('补充思考',{exact:true}).fill('我想了解预训练');await page.getByRole('button',{name:'发送补充'}).click();await page.getByText('我想了解预训练',{exact:true}).waitFor();await page.getByRole('button',{name:'返回记录'}).click();
await page.locator('nav [data-tab=progress]').click();await page.locator('.progress-card').first().waitFor();await page.screenshot({path:`outputs/${engine}-progress.png`});
await page.locator('nav [data-tab=inbox]').click();await page.getByRole('button',{name:'搜索记录',exact:true}).click();await page.getByRole('textbox',{name:'搜索记录',exact:true}).fill(engine);assert.equal(await page.locator('.card').count(),1);await page.getByRole('button',{name:'取消',exact:true}).click();
await page.screenshot({path:`outputs/${engine}-inbox.png`});
await page.locator('.card').filter({hasText:engine}).click();await page.getByRole('button',{name:'我已完成',exact:true}).click();await page.getByRole('button',{name:'重新打开',exact:true}).waitFor();await page.getByRole('button',{name:'返回记录'}).click();await page.getByRole('button',{name:'已完成',exact:true}).click();await page.locator('.card').filter({hasText:engine}).waitFor();
await page.locator('nav [data-tab=settings]').click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出备份'}).click();const file=await download;await file.saveAs(`outputs/${engine}-backup.json`);
const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入记录'}).click();await (await chooser).setFiles(`outputs/${engine}-backup.json`);await page.getByText('已导入 0 条记录，已有记录保持不变',{exact:true}).waitFor();
await page.setViewportSize({width:320,height:740});await page.locator('nav [data-tab=inbox]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`outputs/${engine}-narrow.png`});
await page.setViewportSize({width:1280,height:900});await page.screenshot({path:`outputs/${engine}-desktop.png`});assert.ok(await page.evaluate(()=>{const r=document.querySelector('.bottom-nav').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.width<=680}));
assert.deepEqual(errors,[]);console.log(engine+': create, persistence, drafts, edit restore, settings, model test, AI, reply, progress, search, completion, backup and responsive checks passed');await browser.close();
}}finally{server.kill()}
