import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {Store} from '../lib/store.mjs';import {execute,seal,unseal} from '../lib/service.mjs';import {apply,defaults,DAY,eligible,quiet,validateBackup,endpoint} from '../lib/domain.mjs';import {review} from '../lib/model.mjs';
const secret=Buffer.alloc(32,7).toString('base64');
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_real_slyde.sql',import.meta.url),'utf8'));return {prepare(sql){const q=db.prepare(sql);return {bind(...args){return {async run(){const x=q.run(...args);return {meta:{changes:Number(x.changes)}}},async first(){return q.get(...args)}}}}}}}
const setup=()=>new Store(database(),'alice');
const config={baseUrl:'https://models.example.com/v1',model:'test',apiKey:'fixture-key',searchKey:'',interval:6,quietFrom:22,quietTo:8,enabled:false,search:false};
const good=()=>Response.json({choices:[{message:{content:JSON.stringify({summary:'一个判断',detail:'测试回答，不代表真实模型效果',question:'',nextAction:'research',nextQuery:'进一步研究这个问题'})}}]});
async function ready(s){await execute(s,'settings',config,secret);return (await execute(s,'save',{text:'为什么模型能学习',kind:'think'},secret)).task}
test('save, edit, reply, completion and delete persist with revisions',async()=>{const s=setup();let t=(await execute(s,'save',{text:'一个想法',kind:'note'},secret)).task;assert.equal((await s.read()).data.tasks.length,1);t=(await execute(s,'save',{id:t.id,revision:1,text:'如何理解模型',kind:'think'},secret)).task;await execute(s,'change',{id:t.id,revision:2,action:'reply',content:'补充背景'},secret);await execute(s,'change',{id:t.id,revision:3,action:'done'},secret);await execute(s,'delete',{id:t.id,revision:4},secret);assert.equal((await s.read()).data.tasks.length,0)});
test('users are isolated in same database',async()=>{const db=database(),a=new Store(db,'a'),b=new Store(db,'b');await execute(a,'save',{text:'私有笔记'},secret);assert.equal((await execute(b,'snapshot',{},secret)).snapshot.tasks.length,0)});
test('stale edit is rejected and deletion cannot resurrect note',async()=>{const s=setup(),t=await ready(s);await execute(s,'change',{id:t.id,revision:1,action:'snooze'},secret);await assert.rejects(execute(s,'save',{id:t.id,revision:1,text:'旧版本'},secret),/更新/);await execute(s,'delete',{id:t.id,revision:2},secret);await assert.rejects(execute(s,'save',{id:t.id,revision:2,text:'复活'},secret),/删除/)});
test('secrets encrypted, owner bound, absent from snapshots',async()=>{const s=setup();await ready(s);const stored=(await s.read()).data.config.apiKey;assert.notEqual(stored,'fixture-key');assert.equal(await unseal(stored,secret,'alice'),'fixture-key');await assert.rejects(unseal(stored,secret,'bob'));assert.ok(!JSON.stringify(await execute(s,'snapshot',{},secret)).includes('fixture-key'))});
test('endpoint change cannot silently forward existing key',async()=>{const s=setup();await ready(s);await assert.rejects(execute(s,'settings',{...config,apiKey:'',baseUrl:'https://other.example.com/v1'},secret),/重新填写/)});
test('cloud storage optimistic concurrency preserves both writes',async()=>{const s=setup();await Promise.all([execute(s,'save',{text:'A'},secret),execute(s,'save',{text:'B'},secret)]);assert.equal((await s.read()).data.tasks.length,2)});
test('AI result saved with sources state and next-day scheduling',async()=>{const s=setup(),t=await ready(s);const r=await execute(s,'review',{},secret,async()=>good());const n=r.snapshot.tasks[0];assert.equal(n.events.length,1);assert.equal(n.rounds,1);assert.ok(n.nextReview>=n.lastReview+DAY);assert.equal(n.text,t.text);assert.equal(n.unread,true)});
test('AI old result discarded when original edited during request',async()=>{const s=setup(),t=await ready(s);await execute(s,'review',{},secret,async()=>{await execute(s,'save',{id:t.id,revision:1,text:'新问题',kind:'think'},secret);return good()});const d=(await s.read()).data;assert.equal(d.tasks[0].text,'新问题');assert.equal(d.tasks[0].events.length,0);assert.equal(d.config.history[0].discarded,1)});
test('AI old result discarded when model settings change',async()=>{const s=setup();await ready(s);await execute(s,'review',{},secret,async()=>{await execute(s,'settings',{...config,model:'another'},secret);return good()});assert.equal((await s.read()).data.tasks[0].events.length,0)});
test('provider failure pauses whole pass and releases lease',async()=>{const s=setup();await ready(s);await execute(s,'save',{text:'第二个问题',kind:'think'},secret);let n=0;const r=await execute(s,'review',{},secret,async()=>{n++;return new Response('',{status:401})});assert.equal(n,1);assert.match(r.snapshot.config.blocked,/Key/);assert.equal(r.snapshot.busy,false)});
test('one review max three calls and overlapping review refused',async()=>{const s=setup();await ready(s);for(let i=0;i<4;i++)await execute(s,'save',{text:'问题'+i,kind:'think'},secret);let n=0;await execute(s,'review',{},secret,async()=>{n++;await assert.rejects(execute(s,'review',{},secret,async()=>good()),/正在运行/);return good()});assert.equal(n,3)});
test('quiet hours and frequency prevent automatic requests',async()=>{const s=setup();await ready(s);await execute(s,'settings',{...config,enabled:true},secret);let n=0;await execute(s,'review',{automatic:true,hour:23},secret,async()=>{n++;return good()});assert.equal(n,0);assert.equal(quiet(config,7),true);assert.equal(quiet(config,12),false);assert.equal(quiet({...config,quietFrom:8,quietTo:8},8),false)});
test('waiting for user and three-round cap are respected',()=>{const t={kind:'think',done:false,rounds:3,lastReview:1,nextReview:1};assert.equal(eligible(t,Date.now()),false);assert.equal(eligible({...t,rounds:1,needsUser:true},Date.now()),false)});
test('import is atomic, compatible, idempotent and never overwrites local',async()=>{const s=setup(),t=await ready(s);const b={format:'notenote-backup',version:1,tasks:[{...t,text:'过时原文'},{...t,id:'new',text:'安卓导入'}]};assert.equal((await execute(s,'import',{backup:b},secret)).count,1);assert.equal((await execute(s,'import',{backup:b},secret)).count,0);assert.equal((await s.read()).data.tasks.find(x=>x.id===t.id).text,t.text);await assert.rejects(execute(s,'import',{backup:{...b,tasks:[{...t,id:'will-not-add'},{...t,id:'broken',events:null}]}},secret));assert.equal((await s.read()).data.tasks.length,2)});
test('untrusted model HTML preserved as text; only search response links retained',async()=>{const t={text:'问题',events:[],searchAllowed:true};const c={...config,search:true,searchKey:'search-fixture'};let n=0;const e=await review(t,c,async(url)=>{n++;if(url.includes('tavily'))return Response.json({results:[{url:'javascript:alert(1)',title:'bad'},{url:'https://example.com/article',title:'证据',content:'参考'}]});return Response.json({choices:[{message:{content:JSON.stringify({summary:'<script>bad</script>',detail:'文本',sources:[{url:'https://invented.example.com'}],question:'请补充背景',nextAction:'research',nextQuery:'问题'})}}]})});assert.equal(n,2);assert.equal(e.sources.length,1);assert.equal(e.sources[0].url,'https://example.com/article');assert.equal(e.nextAction,'ask_user');assert.equal(e.nextQuery,'')});
test('unsafe endpoints, invalid backup and malformed model responses rejected',async()=>{for(const url of ['http://example.com','https://127.0.0.1','https://foo.local','https://u:p@example.com'])assert.throws(()=>endpoint(url));assert.throws(()=>validateBackup({tasks:[]}));await assert.rejects(review({text:'问题',events:[]},config,async()=>Response.json({choices:[{message:{content:'not json'}}]})),/结构化/)});
